# Site settings
title: A blog about Web-Developing!
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SUBRAT SAHU
user_description: I am Currently an UnderGrad in Computer Science and Engineering ,from Indian Institute of Technology,Roorkee.I do Web-develpment and Open-Source.
user_title: Developer
email: ssubrat098@gmail.com
twitter_username: subrats41375690
github_username:  subrat-sahu
gplus_username:  subrat sahu
facebook_username: subrat.sahu.1998

# Google-analytics
google-analytics:
  id: "UA-105321274-1"

exclude: ['package.json', 'src' , 'node_modules']
