# Site settings
title: A blog about Web-Developing!
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SUBRAT SAHU
user_description: I am an Undergradute student in CSE at IIT Roorkee, Things I do are Web development, some open0source and also some machine-learning.
gplus_username:  subrat sahu
facebook_username: subrat.sahu.1998

# Google-analytics
google-analytics:
  id: "UA-105321274-1"

exclude: ['package.json', 'src' , 'node_modules']
